### ISSUE TITLE
使用ngx_image_thumb生成缩略图保存起来，不用每次都生成，导致CPU占用很大

### ISSUE THREAD

**Issue by yong472727322** [oupula/ngx_image_thumb#19]
# 你好，请问如何使用ngx_image_thumb把生成的缩略图保存起来，不用每次都生成，导致CPU占用很大

使用image_output off;  直接报404的错误
使用image_output on;  是可以生成缩略图的，但是没有保存起来

**Comment by lmyJavaDE1** [comment]
我也是这个问题，不知怎么解决？

**Comment by oupula** [comment]
注意nginx用户组是否有权限写入图片文件

nginx.conf 查看 user 是 哪个用户

**Comment by yong472727322** [comment]
例子：http://192.168.1.200:1234/group1/M00/00/04/wKgByFoL5JCAKs5CAAKTjdZqEq4291.jpg_500x400.jpg
server{
listen 1234;
client_max_body_size 100m;
#########使用nginx_image_filter生成缩略图并保存在服务器上############################
#第一步：访问缩略图
location ~ '^/group1/M00/([0-9A-F]{2})/([0-9A-F]{2})/(.*)\.(jpg|jpeg|png)_([\d]+)x([\d]+)\.(jpg|jpeg|png)$' {
    #直接从缩略图所在目录查找
    root /home/fastdfs/cache/;
    #如果缩略图不存在，转到生成缩略图的location
    if (!-f $request_filename) {
        #记录变量
        set $width  $5;
        set $height $6;
        set $image_path $1/$2;
        set $image_name $3.$4;
        #把缩略图的尺寸放入请求参数中
        set $image_uri thumb_image/$image_path/$image_name?width=$width&height=$height;
        proxy_pass http://127.0.0.1:$server_port/$image_uri;
    }
    #如果缩略图存在,则直接break,因为缓存缩略图的配置只能写在location的根下
    if (-f $request_filename) {
        break;
    }

    #缓存缩略图
    #缩略图保存目录
    proxy_store       /$request_filename; 
    proxy_store_access   user:rw  group:rw  all:rw;
    proxy_temp_path      /home/fastdfs/cache_temp/;
    proxy_set_header     Host $host;
    proxy_set_header     Content-Type image/jpeg;

}

#第二步：生成缩略图
location /thumb_image {
    #原图目录
    alias /home/fastdfs/data/;
    image_filter resize $arg_width $arg_height;
    image_filter_jpeg_quality 25;                                   # 压缩质量
    image_filter_buffer 20m;                                        # 如果原始图片大小起过1m，则会报415错误
    #不允许外部访问
    allow 127.0.0.0/8;
    deny all;
}

######使用nginx_image_filter生成缩略图并保存在服务器上
#访问原图：匹配FastDFS，不需要缩略图的，直接使用FastDFS即可
location ~*^/group1/M00/.*\.(jpg|jpeg|png)$ {
    ngx_fastdfs_module;
}  

}

**Comment by zhou7286** [comment]
> 注意nginx用户组是否有权限写入图片文件
> 
> nginx.conf 查看 user 是 哪个用户

图片保存的位置呢？下次是不是直接使用？

**Comment by oupula** [comment]
> > 注意nginx用户组是否有权限写入图片文件
> > nginx.conf 查看 user 是 哪个用户
> 
> 图片保存的位置呢？下次是不是直接使用？

保存在图片原图目录，如果文件存在，肯定是直接使用的。
404的话，应该是文件权限问题，导致图片无法生成
